Create Gibbs estimator + tests
zapatacomputing/z-quantum-qaoa pull request #57
Opened 2021-07-13 21:33 UTC by laurgao

- Implement the Gibbs objective function from https://arxiv.org/pdf/1909.07621.pdf
- Move estimators to their own folder

2021-07-14 16:08 UTC, mstechly requested changes

2021-07-14 16:08 UTC, mstechly commented on src/python/zquantum/qaoa/estimators/gibbs_estimator.py
> +class GibbsEstimator(EstimateExpectationValues):
I'd rename it to `GibbsObjectiveEstimator`.

2021-07-14 16:08 UTC, mstechly commented on tests/zquantum/qaoa/estimators/gibbs_estimator_test.py
> +        def custom_run_circuit_and_measure(circuit, n_samples):
We've recently updated how `MockQuantumBackend` works, this whole function is no longer needed, you can just do: `return MockQuantumBackend()`.

2021-07-14 16:08 UTC, mstechly commented on tests/zquantum/qaoa/estimators/gibbs_estimator_test.py
> +    def test_gibbs_estimator_raises_exception_if_alpha_less_than_0(
It's good to add test cases for boundary conditions as well – in this case for `alpha=0`.

2021-07-16 08:31 UTC, alexjuda commented
@laurgao @mstechly what do you folks think about renaming `zquantum.qaoa.estimators.cvar_estimator` into `zquantum.qaoa.estimators._cvar_estimator` and thus separating public/private API by a convention? Anything in `zquantum.qaoa.estimators` would be treated as the public (the functions/classes that we indend our users to freely use in their code). 

BTW this is a convention we started to introduce some time ago in z-quantum-core.

2021-07-16 08:33 UTC, mstechly commented
@alexjuda good idea!

2021-07-16 08:37 UTC, alexjuda commented
@laurgao If you also like this idea it'd be also nice to follow this convention for public/private API split in #56 🙂

2021-07-16 12:06 UTC, laurgao commented
@alexjuda Cool, I'll make the changes. One concern though: for #56, I've seen Farhi ansatz commonly imported using `zquantum.qaoa.ansatzes.farhi_ansatz`, so renaming it will probably break something somewhere. I guess I'll rename the new ansatz file but not the old ones?

2021-07-19 16:12 UTC, mstechly approved these changes

2021-07-19 16:58 UTC, merged