Fourier nested optimizer
zapatacomputing/z-quantum-qaoa pull request #90
Opened 2022-01-31 14:14 UTC by laurgao

2022-02-07 22:32 UTC, mstechly requested changes

2022-02-07 22:32 UTC, mstechly commented on src/python/zquantum/qaoa/parameter_initialization/_fourier.py
> +                can sometimes escape a local optimum. Can be any integer 0 or above. The
Super minor style suggestion
```suggestion
                can sometimes escape a local optimum. Can be any non-negative integer. The
```

2022-02-07 22:32 UTC, mstechly commented on src/python/zquantum/qaoa/parameter_initialization/_fourier.py
> +        if self._q == np.inf:
I think we should change it from inf to `None`, that would be more pythonic.

2022-02-07 22:32 UTC, mstechly commented on src/python/zquantum/qaoa/parameter_initialization/_fourier.py
> +    what we use in this implementation of Fourier.
```suggestion
    what we use as default in this implementation of Fourier.
```

2022-02-09 15:59 UTC, dexter2206 requested changes

2022-02-09 15:59 UTC, dexter2206 commented on tests/zquantum/qaoa/parameter_initialization/fourier_test.py
> +class TestFouier:
Typo :) `TestFouier -> TestFourier`

2022-02-09 18:29 UTC, mstechly commented on src/python/zquantum/qaoa/estimators/_cvar_estimator.py
> +    return np.array(np.array(expectation_values_list).sum(axis=0))
Well, the problem is that `np.sum` returns "`np.array` or `number`", but our function should return just `np.array`. 
So I added this one `np.array` more to get rid of mypy issue.

2022-02-10 19:51 UTC, mstechly approved these changes

2022-02-10 19:56 UTC, dexter2206 approved these changes

2022-02-10 21:58 UTC, merged